server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eatapp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    adminname: root
    password: QmBZtBQ%T8mo
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates
    cache: false

#整合 mybatis
mybatis:
  #配置别名
  type-aliases-package: com.heng.app.entity
  #配置 xml 文件映射
  mapper-locations: classpath:com/heng/app/mapper/*.xml